Add kustomize application to deploy rag-llm application
validatedpatterns-sandbox/rag-llm-gitops pull request #2
Opened 2024-03-26 23:59 UTC by sauagarwa

2024-03-27 13:33 UTC, claudiol requested changes
@sauagarwa Let's revert the changes to .gitignore and pattern-util.sh.  If we are going to change these files we should do so directly in the **common** repository.  Remember that we use git subtree to include this repo in our patterns.

2024-03-27 13:33 UTC, claudiol commented on common/.gitignore
@sauagarwa If we are going to change this file we should do so directly in the **common** repository.  Remember that we use git subtree to include this repo in our patterns.

2024-03-27 13:33 UTC, claudiol commented on common/scripts/pattern-util.sh
@sauagarwa Same with this file.  It seems there are no real changes to this file ... If we are going to change this file we should do so directly in the **common** repository.  Remember that we use git subtree to include this repo in our patterns.

2024-03-27 14:06 UTC, sauagarwa commented on common/.gitignore
I will revert it back .. i think there is only spacing issue

2024-03-27 19:47 UTC, sauagarwa commented on common/.gitignore
fixed

2024-03-28 10:51 UTC, claudiol commented
Merging. This patterns needs nodes that include access to GPUs.  We will add that in the documentation of the pattern.

2024-03-28 10:52 UTC, merged